---
- name: Parchar y reiniciar servidores
  hosts: web
  become: true
  vars:
    yum_name: "*"
    yum_state: latest
    yum_enablerepo: "rhel-?-server-rpms,rhel-?-server-satellite-tools-6.?-rpms"
    yum_disablerepo: "*"
    yum_exclude: ""
    dnf_name: "*"
    dnf_state: latest
    dnf_enablerepo: "rhel-8-for-x86_64-appstream-rpms,rhel-8-for-x86_64-baseos-rpms,satellite-tools-6.?-for-rhel-8-x86
    telegram_bot_token: "7672331419:AAENA8ZJUyA8tNciuIFqAhuq-wCbkDcoIQA"  # Token de tu bot de Telegram
    telegram_chat_id: "Oasis12_bot"                                         # ID del chat de Telegram

  tasks:
    - name: Actualizar paquetes vía yum
      yum:
        name: "{{ yum_name }}"
        state: "{{ yum_state }}"
        disablerepo: "{{ yum_disablerepo }}"
        enablerepo: "{{ yum_enablerepo }}"
        exclude: "{{ yum_exclude }}"
      register: yum_update
      when:
        - (ansible_facts['distribution_major_version'] == '6') or (ansible_facts['distribution_major_version'] == '7')

    - name: Mostrar errores de yum si ocurrieron
      debug:
        msg: "El comando yum produjo errores"
      when: yum_update is not defined

    - name: Actualizar paquetes vía dnf
      dnf:
        name: "{{ dnf_name }}"
        state: "{{ dnf_state }}"
        disablerepo: "{{ dnf_disablerepo }}"
        enablerepo: "{{ dnf_enablerepo }}"
        exclude: "{{ dnf_exclude }}"
      register: dnf_update
      when:
        - ansible_facts['distribution_major_version'] == '8'

    - name: Mostrar errores de dnf si ocurrieron
      debug:
        msg: "El comando dnf produjo errores"
      when: dnf_update is not defined

    - name: Verificar si es
