---
- name: Playbook para parchar servidores Linux
  hosts: all
  become: true
  vars:
    telegram_bot_token: "7672331419:AAENA8ZJUyA8tNciuIFqAhuq-wCbkDcoIQA"   # Reemplaza con tu token
    telegram_chat_id: "Oasis12_bot"                 # Reemplaza con tu chat ID
  tasks:

    - name: Actualizar los paquetes a la última versión
      ansible.builtin.yum:
        name: "*"
        state: latest
      register: update_result
      ignore_errors: true  # Permitir que el playbook continúe incluso si falla

    - name: Verificar si es necesario reiniciar el servidor (RHEL-based)
      ansible.builtin.shell: |
        needs-restarting -r; echo $?
      register: reboot_required_check
      changed_when: reboot_required_check.stdout == "0"  # Si el comando devuelve 0, significa que se requiere reinicio
      failed_when: reboot_required_check.rc not in [0, 1]  # Permitir sólo códigos de retorno 0 o 1

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.reboot:
        msg: "Reiniciando el servidor debido a la actualización de paquetes"
        reboot_timeout: 600
      when: reboot_required_check.stdout == "0"  # Comprobar si se requiere reinicio

    - name: Esperar a que el servidor esté disponible después del reinicio
      ansible.builtin.wait_for_connection:
        timeout: 300
      when: reboot_required_check.stdout == "0"  # Comprobar si se requiere reinicio

    - name: Ejecutar pruebas post-actualización
      ansible.builtin.shell: |
        echo "Iniciando pruebas post-actualización"
        ping -c 4 8.8.8.8
        systemctl status sshd
      register: post_update_checks
      ignore_errors: true  # Ignorar errores en las pruebas post-actualización

    - name: Enviar resultados de actualización a Telegram
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "chat_id": "{{ telegram_chat_id }}",
            "text": "Resultado de la actualización:\n{{ post_update_checks.stdout }}"
          }
      delegate_to: localhost
