---
- name: Playbook para parchar servidores Linux
  hosts: all
  become: true
  vars:
    telegram_bot_token: "TU_TELEGRAM_BOT_TOKEN"
    telegram_chat_id: "TU_CHAT_ID"
    packages:
      - "*"
  
  tasks:

    - name: Actualizar los paquetes a la última versión
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      register: update_result
      loop: "{{ packages }}"
      ignore_errors: true

    - name: Verificar si es necesario reiniciar el servidor
      ansible.builtin.shell: |
        if [ -f /var/run/reboot-required ]; then
          echo "Reboot Required";
        else
          echo "No Reboot Required";
        fi
      register: reboot_required_check
      changed_when: "'Reboot Required' in reboot_required_check.stdout"

    - name: Reiniciar el servidor si es necesario
      ansible.builtin.reboot:
        msg: "Reiniciando el servidor debido a la actualización de paquetes"
        reboot_timeout: 600
      when: "'Reboot Required' in reboot_required_check.stdout"

    - name: Esperar a que el servidor esté disponible después del reinicio
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Ejecutar pruebas post-actualización
      ansible.builtin.shell: |
        echo "Iniciando pruebas post-actualización"
        # Aquí se pueden agregar los comandos de pruebas necesarios
        echo "Prueba de conectividad a la red"
        ping -c 4 8.8.8.8
        echo "Verificación de servicios"
        systemctl status sshd
      register: post_update_checks

    - name: Enviar resultados de actualización a Telegr
