---
- name: Playbook para parchar servidores Linux
  hosts: all
  become: true
  vars:
    telegram_bot_token: "TU_TELEGRAM_BOT_TOKEN"
    telegram_chat_id: "TU_CHAT_ID"
    packages:
      - "*"
  
  tasks:

    - name: Actualizar los paquetes a la última versión
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      register: update_result
      loop: "{{ packages }}"
