---
- name: Install required Python modules for package management
  hosts: all
  become: true

  tasks:
    - name: Install Python 3 and required packages on RedHat-based systems
      ansible.builtin.yum:
        name: 
          - python3
          - python3-dnf
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Python 3 and required packages on Debian-based systems
      ansible.builtin.apt:
        name: 
          - python3
          - python3-apt
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Check if 'dnf' Python module is installed on RedHat-based systems
      ansible.builtin.command: python3 -m dnf
      ignore_errors: true
      register: dnf_check
      when: ansible_facts['os_family'] == "RedHat"

    - name: Print message if 'python3-dnf' is missing on RedHat
      ansible.builtin.debug:
        msg: "'python3-dnf' module is not installed on this system. Please install it manually."
      when: dnf_check.failed and ansible_facts['os_family'] == "RedHat"
