---
- name: Install required Python modules for package management
  hosts: all
  become: true

  tasks:
    - name: Instalar el paquete 'python3-dnf' en sistemas basados en RedHat
      ansible.builtin.yum:
        name: python3-dnf
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Instalar el paquete 'python3-apt' en sistemas basados en Debian
      ansible.builtin.apt:
        name: python3-apt
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
